import { Observable } from 'rxjs';

/**
 * Wire shape of one row on the `/observability/:symbol` timeline. Mirror of the backend
 * `NarrativeObservationDto` (Phase 3 #1). Each row pairs a past narrative with what the price
 * did afterwards at 1d / 1w / 1m horizons, so the user can scroll the dossier history and judge
 * « was the LLM right ? » without leaving the page.
 *
 * **Nullable fields, by design** :
 * - `promptTemplateId / promptName / promptTemplateVersion` are null for snapshots generated
 *   before the V8 backfill (legacy `prompt_version = 'v1'`) or under the fallback prompt path.
 *   The page hides the prompt chip in that case rather than rendering an « unknown » label.
 * - `thumbsValue` is null when no `prompt_score` row exists for the snapshot (fallback path /
 *   pre-PR2 history). The page hides the thumbs chip ; clicking through to the snapshot would
 *   still surface the 👍/👎 buttons via the existing dossier feedback flow.
 * - `priceAt1d / 1w / 1m` and `delta1d / 1w / 1m` are null when the window hasn't elapsed yet
 *   (snapshot from this morning has no « 1m later » data) or the upstream chart fetch failed
 *   (graceful degradation — the narratives stay visible, deltas just don't render).
 *
 * **Numeric encoding** : `delta*` are *fractional* changes (e.g. `0.0234` = +2.34 %). The page
 * is responsible for the percent rendering (typically `PercentPipe`).
 */
export interface NarrativeObservation {
  snapshotId: string;
  symbol: string;
  generatedAt: string; // ISO instant
  price: number;
  summary: string;
  sentiment: 'BULLISH' | 'NEUTRAL' | 'BEARISH';
  keyPoints: string[];
  modelUsed: string;
  promptVersion: string;
  promptTemplateId: string | null;
  promptName: string | null;
  promptTemplateVersion: string | null;
  thumbsValue: number | null;
  priceAt1d: number | null;
  priceAt1w: number | null;
  priceAt1m: number | null;
  delta1d: number | null;
  delta1w: number | null;
  delta1m: number | null;
}

/**
 * Envelope shape mirror of the backend `NarrativeObservationsResponse`. The wrapper is here so
 * we can later layer page-level metadata (active filters echoed back, total count, provider tag)
 * without rewriting the JSON contract the page already binds to.
 */
export interface NarrativeObservations {
  symbol: string;
  observations: NarrativeObservation[];
}

/**
 * Optional filters forwarded to the backend as query params. All optional ; absent fields mean
 * « don't filter on this dimension ». Mirrors the controller's `?from=&to=&promptId=` shape.
 *
 * - `from / to` are ISO instants (open interval : `from` inclusive, `to` exclusive).
 * - `promptId` filters to snapshots generated by a specific `prompt_template` row. Snapshots
 *   with a null `prompt_template_id` (fallback / pre-V8) are excluded when this filter is set.
 */
export interface NarrativeObservationsFilter {
  from?: string;
  to?: string;
  promptId?: string;
}

/**
 * Port — read-only access to the observability timeline. v1 exposes a single endpoint per
 * symbol ; the filters are forwarded as query params. PR3 will add the « tickers index » endpoint
 * to list the symbols with at least one snapshot, but for now the page is reachable only via a
 * direct URL or a link from the dossier ticker (the latter wired in PR3 too).
 */
export abstract class NarrativeObservabilityRepository {
  abstract findFor(
    symbol: string,
    filter?: NarrativeObservationsFilter,
  ): Observable<NarrativeObservations>;
}
