package com.portfolioai.analysis.application.dto

import com.portfolioai.analysis.domain.Sentiment
import com.portfolioai.analysis.domain.SentimentChange
import com.portfolioai.analysis.domain.Verdict
import java.math.BigDecimal
import java.time.Instant
import java.util.UUID

/**
 * Phase 3 #1 — one row on the per-ticker observability timeline. Pairs a past narrative (what the
 * LLM said) with what the price did afterwards (1d / 1w / 1m later), so the user can scroll the
 * dossier history and judge « was the LLM right ? » at a glance.
 *
 * Two enrichments on top of the raw [TickerNarrativeSnapshotDto] :
 *
 * 1. **Prompt provenance** — `promptName` / `promptTemplateVersion` joined from `prompt_template`.
 *    Lets the page filter « narratives generated by v3 vs v4 » without a second round-trip. Null
 *    when the snapshot's FK is null (pre-V8 snapshots or fallback prompt path).
 * 2. **User thumbs** — the latest `prompt_score.user_thumbs` for this snapshot. `null` when no
 *    score row exists (fallback path, or snapshot generated before PR2 wired the recorder).
 *
 * Plus the **price-since enrichment**, computed at render time by
 * [com.portfolioai.analysis.application.NarrativeObservabilityService] from the cached 1Y chart :
 *
 * - `priceAt1d / 1w / 1m` — close of the first available bar at or after generation + offset.
 * - `delta1d / 1w / 1m` — fractional change vs the snapshot's recorded `price` (e.g. `0.0234` =
 *   +2.34 %).
 *
 * All six fields are nullable : the window may not have elapsed yet (snapshot from this morning, no
 * 1d bar), the bar series may not reach back that far (1Y chart vs a 2-year-old snapshot), or the
 * upstream may be unavailable (we degrade gracefully — better an observability list without deltas
 * than a 503 hiding the narratives the user came to read).
 */
data class NarrativeObservationDto(
  val snapshotId: UUID,
  val symbol: String,
  val generatedAt: Instant,
  val price: BigDecimal,
  val summary: String,
  val sentiment: Sentiment,
  val keyPoints: List<String>,
  val modelUsed: String,
  val promptVersion: String,
  val promptTemplateId: UUID?,
  val promptName: String?,
  val promptTemplateVersion: String?,
  val thumbsValue: Short?,
  val priceAt1d: BigDecimal?,
  val priceAt1w: BigDecimal?,
  val priceAt1m: BigDecimal?,
  val delta1d: BigDecimal?,
  val delta1w: BigDecimal?,
  val delta1m: BigDecimal?,
  /**
   * Phase 3 #2 — coherence score against the chronologically-previous snapshot of the same ticker.
   * `null` for the oldest snapshot in the timeline (no previous to compare against). The page
   * renders a colored chip on each card from the verdict, with the sub-measures in the tooltip.
   */
  val coherence: CoherenceScoreDto? = null,
)

/**
 * Phase 3 #2 — wire shape of the coherence score for one snapshot vs the previous one. Mirrors
 * [com.portfolioai.analysis.domain.CoherenceScore] but encoded for JSON :
 *
 * - [verdict] / [sentimentChange] are serialised as their `enum.name()` (BULLISH-style strings),
 * - [keyPointsJaccard] is in `[0..1]` (1 = identical key_points sets),
 * - [summaryLengthRatio] is `current.summary.length / previous.summary.length` (1 = same length),
 * - [priceMoveBetween] is fractional (`0.0234` = +2.34 % move between the two runs), nullable when
 *   the previous snapshot's price was non-positive (defensive).
 */
data class CoherenceScoreDto(
  val verdict: Verdict,
  val sentimentChange: SentimentChange,
  val keyPointsJaccard: BigDecimal,
  val summaryLengthRatio: BigDecimal,
  val priceMoveBetween: BigDecimal?,
  val previousSnapshotId: UUID,
  val previousGeneratedAt: Instant,
)

/**
 * Wraps the timeline in a small envelope so we can layer page-level metadata later (active filters
 * echoed back, total count for pagination, source provider, …) without rewriting the JSON shape the
 * frontend already consumes.
 */
data class NarrativeObservationsResponse(
  val symbol: String,
  val observations: List<NarrativeObservationDto>,
)

/**
 * One row on the `/observability` index page — a ticker with at least one persisted narrative. The
 * page renders these as cards / list items linking to the per-symbol timeline.
 *
 * - [snapshotCount] surfaces « how much history exists ? » so the user can prioritise tickers with
 *   a richer corpus.
 * - [lastGeneratedAt] drives the sort (most-recent first) and lets the page show a relative
 *   timestamp (« 2 days ago ») without re-fetching the timeline itself.
 */
data class TickerObservationIndexDto(
  val symbol: String,
  val snapshotCount: Int,
  val lastGeneratedAt: Instant,
)
