package com.portfolioai.analysis.infrastructure.http

import com.portfolioai.analysis.application.NarrativeObservabilityService
import com.portfolioai.analysis.application.dto.NarrativeObservationsResponse
import io.swagger.v3.oas.annotations.tags.Tag
import java.time.Instant
import java.util.UUID
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController

/**
 * Phase 3 #1 — backend endpoint for the « narrative vs price » observability page. The Angular page
 * `/observability/:symbol` calls this to render a reverse-chronological timeline of past
 * narratives, each paired with the price action since (1d / 1w / 1m).
 *
 * **Filters** mirror the page UI :
 *
 * - `from` / `to` — ISO 8601 timestamps (`2026-04-01T00:00:00Z`). Optional ; the page's date range
 *   chip selector forwards both when set. Open intervals : `from` inclusive, `to` exclusive.
 * - `promptId` — UUID of a specific `prompt_template`. Optional ; the page's prompt selector
 *   forwards it when filtering to « narratives generated by prompt v3 ». Snapshots whose
 *   `prompt_template_id` is null are excluded when this filter is set.
 *
 * No pagination today — the query layer caps at 500 rows which covers ~3 years of daily narratives
 * on a single symbol, well above realistic single-user volume. The date range filter is the escape
 * hatch if we ever cross that threshold.
 */
@Tag(
  name = "Narrative Observability",
  description =
    "Phase 3 #1 — timeline of past narratives for a ticker, enriched with price action since",
)
@RestController
@RequestMapping("/api/narrative/observability")
class NarrativeObservabilityController(private val service: NarrativeObservabilityService) {

  // `Instant` query params bind via Spring's default `InstantFormatter` (uses `Instant.parse`),
  // so the wire format is ISO 8601 with a trailing `Z` or offset (e.g. `2026-04-01T00:00:00Z`).
  // No `@DateTimeFormat` needed — the default converter handles this verbatim.
  @GetMapping("/{symbol}")
  fun observe(
    @PathVariable symbol: String,
    @RequestParam(required = false) from: Instant?,
    @RequestParam(required = false) to: Instant?,
    @RequestParam(name = "promptId", required = false) promptTemplateId: UUID?,
  ): NarrativeObservationsResponse =
    service.findFor(symbol = symbol, from = from, to = to, promptTemplateId = promptTemplateId)
}
