package com.portfolioai.analysis.infrastructure.http

import com.portfolioai.analysis.application.NarrativeBiasService
import com.portfolioai.analysis.application.NarrativeObservabilityService
import com.portfolioai.analysis.application.dto.NarrativeBiasResponse
import com.portfolioai.analysis.application.dto.NarrativeObservationsResponse
import com.portfolioai.analysis.application.dto.TickerObservationIndexDto
import io.swagger.v3.oas.annotations.tags.Tag
import java.time.Instant
import java.util.UUID
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController

/**
 * Phase 3 #1 — backend surface for the « narrative vs price » observability pages. Two endpoints :
 *
 * - **`GET /api/narrative/observability/tickers`** — list of symbols with ≥ 1 persisted narrative
 *   (Phase 3 #1 PR3). Backs the `/observability` index page.
 * - **`GET /api/narrative/observability/{symbol}`** — reverse-chronological timeline of past
 *   narratives for a ticker, each paired with the price action since (1d / 1w / 1m). Backs the
 *   per-symbol page `/observability/:symbol`.
 *
 * **Filters on the per-symbol endpoint** mirror the page UI :
 *
 * - `from` / `to` — ISO 8601 timestamps (`2026-04-01T00:00:00Z`). Optional ; the page's date range
 *   chip selector forwards both when set. Open intervals : `from` inclusive, `to` exclusive.
 * - `promptId` — UUID of a specific `prompt_template`. Optional ; the page's prompt selector
 *   forwards it when filtering to « narratives generated by prompt v3 ». Snapshots whose
 *   `prompt_template_id` is null are excluded when this filter is set.
 *
 * The thumbs filter is intentionally **not** a server-side parameter — it's a small in-memory scan
 * over the already-returned timeline (typically < 100 rows on a single symbol). Keeping it
 * client-side avoids re-fetching when the user toggles thumb chips and keeps the API surface
 * narrow.
 *
 * No pagination today — the query layer caps at 500 rows which covers ~3 years of daily narratives
 * on a single symbol, well above realistic single-user volume. The date range filter is the escape
 * hatch if we ever cross that threshold.
 */
@Tag(
  name = "Narrative Observability",
  description =
    "Phase 3 #1 — timeline of past narratives for a ticker, enriched with price action since",
)
@RestController
@RequestMapping("/api/narrative/observability")
class NarrativeObservabilityController(
  private val service: NarrativeObservabilityService,
  private val biasService: NarrativeBiasService,
) {

  /**
   * Phase 3 #1 PR3 — index of tickers that have at least one persisted narrative. Backs the
   * `/observability` landing page (no symbol). Ordered most-recent first.
   *
   * Declared **before** the `/{symbol}` route so Spring matches the literal segment first ; without
   * it, a path like `/api/narrative/observability/tickers` would otherwise bind `tickers` as the
   * `symbol` path variable and return an empty timeline.
   */
  @GetMapping("/tickers") fun listTickers(): List<TickerObservationIndexDto> = service.listTickers()

  /**
   * Phase 3 #3 — narrative bias dashboard endpoint. Aggregates the corpus across symbols and
   * returns four sections : sentiment distribution (with bias flag at 60 %), calibration of
   * sentiment vs subsequent price action, top-N key_points topics, and thumbs distribution by
   * sentiment. Filters mirror the timeline endpoint (`from / to / promptId`) so the page can reuse
   * the same filter UI.
   *
   * Declared **before** `/{symbol}` for the same reason as `/tickers` — keeps Spring routing
   * unambiguous on the literal path segment.
   */
  @GetMapping("/bias")
  fun bias(
    @RequestParam(required = false) from: Instant?,
    @RequestParam(required = false) to: Instant?,
    @RequestParam(name = "promptId", required = false) promptTemplateId: UUID?,
  ): NarrativeBiasResponse =
    biasService.computeBias(from = from, to = to, promptTemplateId = promptTemplateId)

  // `Instant` query params bind via Spring's default `InstantFormatter` (uses `Instant.parse`),
  // so the wire format is ISO 8601 with a trailing `Z` or offset (e.g. `2026-04-01T00:00:00Z`).
  // No `@DateTimeFormat` needed — the default converter handles this verbatim.
  @GetMapping("/{symbol}")
  fun observe(
    @PathVariable symbol: String,
    @RequestParam(required = false) from: Instant?,
    @RequestParam(required = false) to: Instant?,
    @RequestParam(name = "promptId", required = false) promptTemplateId: UUID?,
  ): NarrativeObservationsResponse =
    service.findFor(symbol = symbol, from = from, to = to, promptTemplateId = promptTemplateId)
}
