import { Observable } from 'rxjs';

/**
 * Wire shape of one row on the `/observability/:symbol` timeline. Mirror of the backend
 * `NarrativeObservationDto` (Phase 3 #1). Each row pairs a past narrative with what the price
 * did afterwards at 1d / 1w / 1m horizons, so the user can scroll the dossier history and judge
 * « was the LLM right ? » without leaving the page.
 *
 * **Nullable fields, by design** :
 * - `promptTemplateId / promptName / promptTemplateVersion` are null for snapshots generated
 *   before the V8 backfill (legacy `prompt_version = 'v1'`) or under the fallback prompt path.
 *   The page hides the prompt chip in that case rather than rendering an « unknown » label.
 * - `thumbsValue` is null when no `prompt_score` row exists for the snapshot (fallback path /
 *   pre-PR2 history). The page hides the thumbs chip ; clicking through to the snapshot would
 *   still surface the 👍/👎 buttons via the existing dossier feedback flow.
 * - `priceAt1d / 1w / 1m` and `delta1d / 1w / 1m` are null when the window hasn't elapsed yet
 *   (snapshot from this morning has no « 1m later » data) or the upstream chart fetch failed
 *   (graceful degradation — the narratives stay visible, deltas just don't render).
 *
 * **Numeric encoding** : `delta*` are *fractional* changes (e.g. `0.0234` = +2.34 %). The page
 * is responsible for the percent rendering (typically `PercentPipe`).
 */
export interface NarrativeObservation {
  snapshotId: string;
  symbol: string;
  generatedAt: string; // ISO instant
  price: number;
  summary: string;
  sentiment: 'BULLISH' | 'NEUTRAL' | 'BEARISH';
  keyPoints: string[];
  modelUsed: string;
  promptVersion: string;
  promptTemplateId: string | null;
  promptName: string | null;
  promptTemplateVersion: string | null;
  thumbsValue: number | null;
  priceAt1d: number | null;
  priceAt1w: number | null;
  priceAt1m: number | null;
  delta1d: number | null;
  delta1w: number | null;
  delta1m: number | null;
  /**
   * Phase 3 #2 — coherence score against the chronologically-previous snapshot of the same
   * ticker. `null` for the oldest snapshot in the timeline (no previous to compare against), and
   * for snapshots returned by a backend version that predates Phase 3 #2 (defensive — the page
   * just hides the chip in that case).
   */
  coherence: CoherenceScore | null;
}

/**
 * Phase 3 #2 — wire shape of the coherence score, mirror of the backend `CoherenceScoreDto`.
 *
 * - [verdict] drives the chip color : `OK` muted/green, `WARN` amber, `HIGH` red.
 * - [sentimentChange] / [keyPointsJaccard] / [summaryLengthRatio] / [priceMoveBetween] are surfaced
 *   in the chip's tooltip so the user can read the why behind the verdict at a glance.
 * - [keyPointsJaccard] is in `[0..1]` (1 = identical key_points sets).
 * - [summaryLengthRatio] is `current.length / previous.length` (1 = same length).
 * - [priceMoveBetween] is fractional (`0.0234` = +2.34 % move between the two runs), `null` only
 *   when the previous snapshot's price was non-positive (defensive).
 */
export interface CoherenceScore {
  verdict: 'OK' | 'WARN' | 'HIGH';
  sentimentChange: 'SAME' | 'PARTIAL' | 'FLIPPED';
  keyPointsJaccard: number;
  summaryLengthRatio: number;
  priceMoveBetween: number | null;
  previousSnapshotId: string;
  previousGeneratedAt: string; // ISO instant
}

/**
 * Envelope shape mirror of the backend `NarrativeObservationsResponse`. The wrapper is here so
 * we can later layer page-level metadata (active filters echoed back, total count, provider tag)
 * without rewriting the JSON contract the page already binds to.
 */
export interface NarrativeObservations {
  symbol: string;
  observations: NarrativeObservation[];
}

/**
 * Optional filters forwarded to the backend as query params. All optional ; absent fields mean
 * « don't filter on this dimension ». Mirrors the controller's `?from=&to=&promptId=` shape.
 *
 * - `from / to` are ISO instants (open interval : `from` inclusive, `to` exclusive).
 * - `promptId` filters to snapshots generated by a specific `prompt_template` row. Snapshots
 *   with a null `prompt_template_id` (fallback / pre-V8) are excluded when this filter is set.
 */
export interface NarrativeObservationsFilter {
  from?: string;
  to?: string;
  promptId?: string;
}

/**
 * One entry on the `/observability` index page (Phase 3 #1 PR3) — a ticker that has at least
 * one persisted narrative. Mirror of the backend `TickerObservationIndexDto`.
 *
 * - `snapshotCount` surfaces « how much history exists ? » so the user can prioritise tickers
 *   with a richer corpus.
 * - `lastGeneratedAt` drives the sort (most-recent first) and lets the page render a relative
 *   timestamp (« 2 days ago ») without re-fetching the timeline itself.
 */
export interface TickerObservationIndex {
  symbol: string;
  snapshotCount: number;
  lastGeneratedAt: string; // ISO instant
}

/**
 * Port — read access to the observability surfaces. Two methods :
 *
 * - [findFor] — per-symbol timeline (PR2), filtered by optional date range + prompt id.
 * - [findTickers] — index of symbols that have at least one snapshot (PR3). Backs the
 *   `/observability` landing page so the user can discover which tickers have history to
 *   inspect without typing a symbol blindly.
 */
export abstract class NarrativeObservabilityRepository {
  abstract findFor(
    symbol: string,
    filter?: NarrativeObservationsFilter,
  ): Observable<NarrativeObservations>;
  abstract findTickers(): Observable<TickerObservationIndex[]>;
}
